
# For help with configuration see https://github.com/rszyma/kanata-tray/blob/main/README.md
"$schema" = "https://raw.githubusercontent.com/rszyma/kanata-tray/main/doc/config_schema.json"

general.allow_concurrent_presets = false
defaults.tcp_port = 4444

[defaults.hooks]
# Hooks allow running custom commands on specific events (e.g. when starting preset).
# Documentation: https://github.com/rszyma/kanata-tray/blob/main/doc/hooks.md

[defaults.layer_icons]
insert = 'l_insert.ico'
navigation = 'l_navigation.ico'
visual = 'l_visual.ico'
os_mac = 'l_os_mac.ico'
default = 'l_default.ico'

[presets.'Default Preset']
# ln -s SOURCE TARGET
# ln -s /Users/slava/Repos/Other/CleanMachineSetup/config_files/Kanata/mac/kanata-tray.toml '/Users/slava/Library/Application Support/kanata-tray/kanata-tray.toml'
kanata_executable = '/opt/homebrew/bin/kanata'
kanata_config = '/Users/slava/Repos/Other/CleanMachineSetup/config_files/Kanata/mac/layout_mac.kbd'
autorun = true

