
# For help with configuration see https://github.com/rszyma/kanata-tray/blob/main/README.md
"$schema" = "https://raw.githubusercontent.com/rszyma/kanata-tray/main/doc/config_schema.json"

general.allow_concurrent_presets = false
defaults.tcp_port = 4445

[defaults.hooks]
# Hooks allow running custom commands on specific events (e.g. when starting preset).
# Documentation: https://github.com/rszyma/kanata-tray/blob/main/doc/hooks.md

[defaults.layer_icons]
insert = 'l_insert.ico'
navigation = 'l_navigation.ico'
visual = 'l_visual.ico'
os_win = 'l_os_win.ico'

[presets.'Default Preset']
kanata_executable = 'C:\MyData\Tools\kanata.exe'

# mklink 'C:\Users\slava\AppData\Roaming\kanata-tray\kanata-tray.toml' 'Z:\Repos\Other\CleanMachineSetup\config_files\Kanata\windows\kanata-tray.toml'
# New-Item -ItemType SymbolicLink -Path 'C:\Users\slava\AppData\Roaming\kanata-tray\kanata-tray.toml' -Target 'Z:\Repos\Other\CleanMachineSetup\config_files\Kanata\windows\kanata-tray.toml'
kanata_config = 'Z:\Repos\Other\CleanMachineSetup\config_files\Kanata\windows\layout_win.kbd'
autorun = true

